workspace = { }

[package]
name = "wry"
version = "0.13.1"
authors = [ "Tauri Programme within The Commons Conservancy" ]
edition = "2021"
license = "Apache-2.0 OR MIT"
description = "Cross-platform WebView rendering library"
readme = "README.md"
repository = "https://github.com/tauri-apps/wry"
documentation = "https://docs.rs/wry"
categories = [ "gui" ]

[package.metadata.docs.rs]
features = [ "dox" ]
default-target = "x86_64-unknown-linux-gnu"
targets = [
  "x86_64-pc-windows-msvc",
  "x86_64-unknown-linux-gnu",
  "x86_64-apple-darwin"
]

[features]
default = [ "file-drop", "protocol" ]
file-drop = [ ]
protocol = [ ]
dox = [ "tao/dox" ]
tray = [ "tao/tray" ]
ayatana = [ "tao/ayatana" ]
devtool = [ ]
transparent = [ ]
fullscreen = [ ]

[patch.crates-io]
tao = { git = "https://github.com/wravery/tao", branch = "windows-0.32.0" }
webview2-com = { git = "https://github.com/wravery/webview2-rs", branch = "windows-0.32.0" }
webview2-com-macros = { git = "https://github.com/wravery/webview2-rs", branch = "windows-0.32.0" }
webview2-com-sys = { git = "https://github.com/wravery/webview2-rs", branch = "windows-0.32.0" }

[dependencies]
libc = "0.2"
log = "0.4"
once_cell = "1.9"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = "1.0"
thiserror = "1.0"
url = "2.2"
tao = { version = "0.6", default-features = false, features = [ "serde" ] }
http = "0.2.6"

[dev-dependencies]
anyhow = "1.0.43"
tempfile = "3.3.0"
http-range = "0.1.4"

[target."cfg(any(target_os = \"linux\", target_os = \"dragonfly\", target_os = \"freebsd\", target_os = \"openbsd\", target_os = \"netbsd\"))".dependencies]
webkit2gtk = { version = "0.17", features = [ "v2_22" ] }
webkit2gtk-sys = "0.17"
gio = "0.15"
glib = "0.15"
gtk = "0.15"
gdk = "0.15"

[target."cfg(target_os = \"windows\")".dependencies]
webview2-com = "0.13.0"
windows-implement = "0.32.0"
sys-info = "0.9"
tempfile-istream = "1.0.2"

  [target."cfg(target_os = \"windows\")".dependencies.windows]
  version = "0.32.0"
  features = [
  "alloc",
  "implement",
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
  "Win32_System_Com",
  "Win32_System_Com_StructuredStorage",
  "Win32_System_Ole",
  "Win32_System_SystemServices",
  "Win32_UI_Shell",
  "Win32_UI_WindowsAndMessaging"
]

[target."cfg(any(target_os = \"ios\", target_os = \"macos\"))".dependencies]
cocoa = "0.24"
core-graphics = "0.22"
objc = { version = "0.2", features = [ "exception" ] }
objc_id = "0.1"
